### PR TITLE
Correctly support Gradle's configuration cache

### LINKED ISSUE #177: Fail on execute AntlrKotlinTask with Gradle 8.7
I tried to run the Gradle task `AntlrKotlinTask`, but it failed.

I'm using gradle 8.7 with kotlin dsl and Java 21. I have applied plugin and add dependency. Kotlin multiplatform (JVM + JS).

Configuration cache - turn on. When cache turn off - task is always "UP-TO-DATE"

```kotlin
val generateGrammarSource by
tasks.registering(AntlrKotlinTask::class) {
//    maxHeapSize = "64m"
    arguments = arguments + listOf("-Dlanguage=Kotlin", "-visitor")
    source =
        project.objects
            .sourceDirectorySet("antlr", "antlr")
            .srcDir("src/commonAntlr/antlr")
            .apply { include("*.g4") }

    val pkgName = "com.strumenta.antlrkotlin.parsers.generated"
    packageName = pkgName

    // outputDirectory is required, put it into the build directory
    // if you do not want to add the generated sources to version control
    outputDirectory = File("build/generated-src/commonAntlr/kotlin")
}
```

Gradle Error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache state could not be cached: field `logger` of `org.gradle.internal.logging.source.JavaUtilLoggingSystem` bean found in field `loggingSystem` of `org.gradle.internal.logging.services.DefaultLoggingManager$StartableLoggingSystem` bean found in field `javaUtilLoggingSystem` of `org.gradle.internal.logging.services.DefaultLoggingManager` bean found in field `loggingManager` of `org.gradle.process.internal.worker.DefaultWorkerProcessFactory` bean found in field `workerProcessBuilderFactory` of task `:common:expression:generateGrammarSource` of type `com.strumenta.antlrkotlin.gradle.AntlrKotlinTask`: error writing value of type 'java.util.logging.LogManager$RootLogger'
> Unable to make field final java.util.logging.LogManager java.util.logging.LogManager$RootLogger.this$0 accessible: module java.logging does not "opens java.util.logging" to unnamed module @67c339bb
```

I've tried to open all necessary java modules.

```  
--add-opens=java.logging/java.util.logging=ALL-UNNAMED --add-opens java.locks/java.util.concurrent.locks=ALL-UNNAMED --add-opens java.base/java.util.concurrent.locks=ALL-UNNAMED --add-opens java.base/java.lang.ref=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.base/sun.util.calendar=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED
```

There is another error: 
```
Could not load the value of field `m` of `java.util.Collections$SynchronizedMap` bean found in field `listeners` of `java.util.logging.LogManager` bean found in field `this$0` of `java.util.logging.LogManager$RootLogger` bean found in field `logger` of `org.gradle.internal.logging.source.JavaUtilLoggingSystem` bean found in field `loggingSystem` of `org.gradle.internal.logging.services.DefaultLoggingManager$StartableLoggingSystem` bean found in field `javaUtilLoggingSystem` of `org.gradle.internal.logging.services.DefaultLoggingManager` bean found in field `loggingManager` of `org.gradle.process.internal.worker.DefaultWorkerProcessFactory` bean found in field `workerProcessBuilderFactory` of task `:common:expression:generateGrammarSource` of type `com.strumenta.antlrkotlin.gradle.AntlrKotlinTask`.
```

Gradle: configuration cache report in attachment (Github not allow to attach html, so please, change file type to html to view report). If you need any details, please let me know.

[configuration-cache-report.log](https://github.com/Strumenta/antlr-kotlin/files/14873826/configuration-cache-report.log)

### PR DESCRIPTION
**Pull request by lppedd**
Fixes #177

### CODE REVIEW

**Comment by ftomassetti** [comment]
I do not see anything wrong with this and all tests are parsing, so I am going to merge it right away

**Comment by Komdosh** [comment]
> I do not see anything wrong with this and all tests are parsing, so I am going to merge it right away

When new RC will be ready?

**Comment by ftomassetti** [comment]
If you need it, I can do a release today

**Comment by Komdosh** [comment]
Yes, it would be nice

**Comment by ftomassetti** [comment]
1.0.0-RC3 has been published!

**Pull request merged**
