### PR TITLE
Avoid NPE when dealing with visitors

### LINKED ISSUE #182: Generated BaseVisitor does not handle nullable types
Let's say I want a visitor that traverses the tree until it finds a certain kind of node whose text also can be parsed to an `Int`. If no such node is found, null is produced.

I would like to write the following class:

```kotlin
class MaybeIntVisitor : MyBaseVisitor<Int?>() {
    override fun visitMaybeInt(ctx: MyParser.MaybeIntContext): Int? {
        return ctx.text.toIntOrNull()
    }

    override fun shouldVisitNextChild(
        node: RuleNode,
        currentResult: Int?,
    ) = currentResult == null
}
```

Sadly, it's not possible, because all the `visitSomething` methods that I'm not overriding assert that the result is non-null.

```kotlin
public open class MyBaseVisitor<T> : AbstractParseTreeVisitor<T>(), MyVisitor<T> {
    
    // ...
    
    override fun visitMaybeInt(ctx: MyParser.MaybeIntContext): T {
        return this.visitChildren(ctx)!! // overridden by MaybeIntVisitor
    }
    
    override fun visitSomeOtherThing(ctx: MyParser.SomeOtherThingContext): T {
        return this.visitChildren(ctx)!! // <- throws NPE
    }
}
```

This causes a NullPointerException to be thrown.

Could you generate the base visitor in such a way as to make nullable types possible?

### PR DESCRIPTION
**Pull request by lppedd**
This is the idea in practice.

Fixes #182

### CODE REVIEW

**Comment by lppedd** [comment]
@ftomassetti I don't have better ideas, and this looks like it's good enough, so I marked the PR as reviewable.

**Comment by ftomassetti** [comment]
I also do not have better ideas and I did not use visitors in many years. The only comment I can make is that a test for this specific use case would be a nice to have, but I would not consider a requirement for merging this. If I do not hear from you I will just go ahead and merge it on Friday

**Comment by lppedd** [comment]
@ftomassetti added a very simple test case, I think it's sufficient to establish if everything works well together.

Next would be RC4? If everything is ok after a couple weeks, you could release 1.0.0. No point in waiting more time.

**Comment by ftomassetti** [comment]
Thank you @lppedd 

> Next would be RC4? If everything is ok after a couple weeks, you could release 1.0.0. No point in waiting more time.

Yes and yes

**Pull request merged**
