### PR TITLE
Adjust nullability for predicates and actions

### PR DESCRIPTION
**Pull request by lppedd**
Fixes: #157

### CODE REVIEW

**Comment by ftomassetti** [comment]
It looks good, but in general it is very hard for me to review changes to the template. Perhaps having a bit more tests would be useful here

**Comment by lppedd** [comment]
@ftomassetti in this case I've pretty much replicated what the Swift template does. 

But yes, if we can, having some other tests would be better. At some point we'll get there.

**Comment by KvanTTT** [comment]
FYI, I'm not sure it's a correct patch. If I applies it, some tests from ANTLR 5 repository starts to fail (`NullPointerException`). I fixed the problem by [adding](https://github.com/antlr/antlr5/pull/6/commits/766add7fa68724b8f34527a7e30acd947bffc84e#diff-fd05327c91bfc30806ef917ccaca5798bb7023e416b0f015085659e97e41d0f5) `@Suppress("UNSAFE_CALL")` to `private fun <r.name>_sempred(_localctx: <r.ctxType>?, predIndex: Int): Boolean`.

**Comment by lppedd** [comment]
That's strange. Theoretically you should never have a null context at that point.

**Comment by lppedd** [comment]
I'll have a better look after porting back the template fixes.

**Comment by KvanTTT** [comment]
I recommend trying out tests in the ANTLR 5 runtime (my branch regarding integration until it's merged) :)

**Comment by lppedd** [comment]
I'll try. It's just strange that it happens with Kotlin and not with Swift, I've used the exact same nullabilities.

**Comment by lppedd** [comment]
@KvanTTT managed to reproduce also with a MySQL grammar. I'll check what's happening.

**Comment by lppedd** [comment]
@KvanTTT so I was wrong, there are situations where a `null` context is possible.  
In case of the MySQL grammar, a `LexerCustomAction` is executed, which has an `execute` method like:

```kotlin
override fun execute(lexer: Lexer): Unit =
  lexer.action(null, ruleIndex, actionIndex)
```

The lexer in that case is `MySQLLexer`, which overrides the `action` method:

```kotlin
override fun action(_localctx: RuleContext?, ruleIndex: Int, actionIndex: Int) {
    when (ruleIndex) {
        21 -> LOGICAL_OR_OPERATOR_action(_localctx as RuleContext, actionIndex)
        70 -> INT_NUMBER_action(_localctx as RuleContext, actionIndex)
        ...
```

**Comment by KvanTTT** [comment]
Yes, and such situations are also possible in testsuite.

**Pull request merged**
