### PR TITLE
Complete updating license

### LINKED ISSUE #148: Update license descriptions also in POMs and headers
As a follow up of #144 we should update the license description also in:
* POMs (see buildSrc/src/main/kotlin/com/strumenta/antlrkotlin/gradle/ext/MavenPublishBaseExtension.ext.kt)
* The runtime sources (see antlr-kotlin-runtime/src/jsAndWasmSharedMain/kotlin/com/strumenta/antlrkotlin/runtime/WeakHashMap.kt, for example)

### PR DESCRIPTION
**Pull request by ftomassetti**
Fix #148

### CODE REVIEW

**Review by KvanTTT — COMMENTED** [review]
I recommend removing at least end year (2024) from all headers. It's annoying to update it every year and I predict some files will be forgotten. We have such situation in the official ANTLR repo. "No information" looks more proper than "incorrect information" (when a file was edited after end date but header was not). Adding begin and end years to license headers brings little value.

**Comment by lppedd** [comment]
We can use open ranges like `2017-present` and `2024-present`.

**Comment by KvanTTT** [comment]
Ok, nevermind. It looks like they are not supposed to be updated. Anyway, I dislike license headers (they look useless from the user's point of view) at all, but it looks like it's more proper from the point of jurisdiction.

**Comment by lppedd** [comment]
We have the same "issue" on our company projects.  
Asking about headers, we were told to keep them, but with the minimal information possible.  
Each time a file is updated on a consecutive year, that file only has its header updated.

**Comment by ftomassetti** [comment]
I updated the files to specify they copyright apply up to the present

**Comment by lppedd** [comment]
Looks good to me.

**Comment by ftomassetti** [comment]
Thank you both for the review!

**Pull request merged**
