### PR TITLE
some updates

### PR DESCRIPTION
**Pull request by drieks**
Hi,

here are some updates, please let me know if something is not working!

### CODE REVIEW

**Comment by ftomassetti** [comment]
Hi, this PR cannot be merged as it is as the build fail. 
In general it is hard to review a change so large: 249 files were changed in one single PR.
There is good stuff here and I would like to have it merged however first we need to correct the errors making the build fail.

In particular it seems not to find the subprojects anymore, perhaps because you removed the build.gradle files in the subprojects

**Comment by ftomassetti** [comment]
I also do not understand why you moved some files

**Comment by ftomassetti** [comment]
I took some of the commits from this PR and merged them already. For the others I am waiting for answers from the committer

**Comment by drieks** [comment]
Hi,

I converted the gradle build to the new multiplatform layout (https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#project-structure)

This directories:
antlr-kotlin-runtime-common/src/main
antlr-kotlin-runtime-jvm/src/main
antlr-kotlin-runtime-js/src/main

are now located here:
antlr-kotlin-runtime/src/commonMain
antlr-kotlin-runtime/src/jvmMain
antlr-kotlin-runtime/src/jsMain

There is now only one build.gradle file (antlr-kotlin-runtime/build.gradle) not three files.

The travis build failed because I forgot to fix the file ".travis.yml".

The gradle IDEA-Plugin is no longer needed, you can just select "open" in the IDEA start screen. Just select the project directory and it should import it correctly into IDEA.

**Comment by drieks** [comment]
All gradle files are written using kotlin-dsl expect antlr-kotlin-runtime/build.gradle, they are named build.gradle.kts / settings.gradle.kts. Unfortunately, it is currently not possible to write multiplatform, multi project gradle files using kotlin-dsl.

**Comment by ftomassetti** [comment]
Thank you so much for the explanation and the awesome contribution!

**Pull request merged**
