### PR TITLE
fix: add @ ExperimentalStdlibApi on Enum.entries for kotlin 1.9.x.

### PR DESCRIPTION
**Pull request by atsushieno**
This should fix issue #136.

### CODE REVIEW

**Comment by ftomassetti** [comment]
Thank you @atsushieno for your analysis and for this PR. I am going to merge it

**Comment by lppedd** [comment]
Marking these properties with `ExperimentalStdlibApi` is *not* what needs to be done, as you're then asking for every consumer to opt-in, adding an unnecessary step for most.

image

The correct way to handle this is at the consumer level, by opting-in through a compiler flag or via a local `OptIn(...)` annotation.  
This library should *not* propagate opt-ins.

This PR needs to be undone.

**Comment by lppedd** [comment]
Also I'm not sure what's going on, but `entries` isn't experimental in 1.9.

What is experimental is the `enumEntries<T>()` function, which is not used here.  
Example: `enumEntries<css3Lexer.Rules>()`

The root of your problem seems to be elsewhere.

**Comment by atsushieno** [comment]
I ran some [experimental builds](https://github.com/atsushieno/mugene-ng/actions/runs/7417106580) on my project and it seems correct - I'm getting those compilation errors somehow only locally. I'm not very happy with the problem the Gradle or Kotlin toolchains have caused, but I agree that the change is unnecessary.

I'll create another PR to revert it. Sorry for the noise!

**Comment by ftomassetti** [comment]
Thank you @lppedd and @atsushieno . @atsushieno no reason to be sorry, we appreciate the contribution and the explanation. This error was quite misleading. Thank you also for the new PR reverting the change, I will merge it straight away

**Pull request merged**
